### ISSUE TITLE
Caret of Select box looks ugly in the case shown on inner screenshot

### ISSUE THREAD

**Issue by Niaro** [Mindfor/fresh-css#14]
![image](https://cloud.githubusercontent.com/assets/7147943/6662809/b6c750e8-cbe1-11e4-8d01-57a96d3dac64.png)

**Comment by anfomin** [comment]
You mean when width is small?

**Comment by Niaro** [comment]
I mean digits is placed very close to carets...it'd may have some margin or padding, whatever u like)

**Comment by Niaro** [comment]
(( I found another one((
![image](https://cloud.githubusercontent.com/assets/7147943/6663763/a0c1d156-cbeb-11e4-9d9c-ee47f1c09dfb.png)
